### ISSUE TITLE
Update arviz dependency

### ISSUE THREAD

**Issue by michaelbuehlmann** [Astropianist/DustE#1]
Currently, `setup.py` requires a very specific version of arviz (`arviz==0.11.2`). Is it possible to relax this requirements to newer versions? 

arviz 0.11.2 depends on some further outdated packages, which in turn clash with dependencies of more up-to-date packages (main issue being `typing_extensions>=3.7.4.3,<4` in arviz 0.11.2).

Thanks!

**Comment by Astropianist** [comment]
Hi Michael, 

Thanks for bringing this up. I have updated the arviz dependency, and everything works on all of the newest versions of the packages (and I'm using python 3.11). The new release has been made on PyPI as well.
